# Generated by Django 6.1 on 2026-08-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_runs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crawlrun',
            old_name='prices_created',
            new_name='articles_updated',
        ),
        migrations.RemoveField(
            model_name='crawlrun',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='crawlrun',
            name='error_message',
        ),
        migrations.AddField(
            model_name='crawlrun',
            name='errors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crawlrun',
            name='sources',
            field=models.JSONField(default=list),
        ),
    ]
