# Generated by Django 5.1.5 on 2026-08-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_runs', '0002_rename_prices_created_crawlrun_articles_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrun',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
