# Generated by Django 5.1.5 on 2026-08-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_runs', '0003_alter_crawlrun_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlrun',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
