# Generated by Django 5.1.5 on 2026-09-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_runs', '0005_crawlrun_task_id_crawlrun_triggered_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrun',
            name='crawl_type',
            field=models.CharField(choices=[('news', 'News'), ('trading', 'Trading Data'), ('floorsheet', 'Floorsheet'), ('all', 'All')], db_index=True, default='news', max_length=20),
        ),
        migrations.AddField(
            model_name='crawlrun',
            name='floorsheet_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlrun',
            name='floorsheet_found',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlrun',
            name='floorsheet_updated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlrun',
            name='logs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='crawlrun',
            name='prices_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlrun',
            name='prices_updated',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlrun',
            name='target',
            field=models.CharField(blank=True, default='All', max_length=255),
        ),
        migrations.AlterField(
            model_name='crawlrun',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='crawlrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='crawlrun',
            name='task_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
