# Generated by Django 5.1.5 on 2026-09-03 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_runs', '0006_crawlrun_crawl_type_crawlrun_floorsheet_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crawlrun',
            name='prices_found',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='crawlrun',
            name='source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='crawlrun',
            name='crawl_type',
            field=models.CharField(choices=[('news', 'News'), ('trading', 'Trading Data'), ('floorsheet', 'Floorsheet'), ('all', 'All')], default='news', max_length=20),
        ),
        migrations.AlterField(
            model_name='crawlrun',
            name='logs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='crawlrun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='crawlrun',
            name='target',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='crawlrun',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
