# Generated by Django 5.1.5 on 2026-09-04 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_id_alter_trackedcompany_id'),
        ('crawler_runs', '0007_crawlrun_created_at_crawlrun_prices_found_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrun',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_runs', to='companies.company'),
        ),
    ]
