# Generated by Django 5.1.5 on 2026-09-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_runs', '0008_crawlrun_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrun',
            name='process_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
