# Generated by Django 5.1.5 on 2026-09-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler_runs', '0009_crawlrun_process_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrun',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text="Free-form per-run context. The floorsheet crawler writes {'sampled_dates': [...], 'mode': 'sample'|'latest'} here so a run can always be audited against the exact sessions it targeted."),
        ),
        migrations.AlterField(
            model_name='crawlrun',
            name='crawl_type',
            field=models.CharField(choices=[('news', 'News'), ('trading', 'Trading Data'), ('floorsheet', 'Floorsheet'), ('floorsheet_sample', 'Floorsheet (historical sample)'), ('all', 'All')], default='news', max_length=20),
        ),
    ]
