import os

path = 'Backend/apps/users/views.py'
with open(path) as f:
    content = f.read()

old_start = '# ======================================================\n# ROLE PERMISSIONS\n# ======================================================\n\nclass RolePermissionsAPIView(APIView):'
old_end = '                ]\n            }\n        )\n\n\n# ======================================================'

start_idx = content.find(old_start)
end_idx = content.find(old_end, start_idx)

if start_idx == -1 or end_idx == -1:
    print('ERROR: markers not found')
else:
    end_idx = end_idx + len(old_end)
    new_block = (
        '# ======================================================\n'
        '# ROLE PERMISSIONS\n'
        '# ======================================================\n'
        '\n'
        'class RolePermissionDetailAPIView(APIView):\n'
        '    """\n'
        '    GET/PATCH a single built-in editable role\n'
        '    (analyst or viewer).\n'
        '\n'
        '    Admin only.\n'
        '    """\n'
        '\n'
        '    permission_classes = [\n'
        '        IsAdminUserRole\n'
        '    ]\n'
        '\n'
        '    def get_object(self, role_key):\n'
        '        config = (\n'
        '            RolePermissionConfig.objects\n'
        '            .filter(\n'
        '                role_key=role_key,\n'
        '                is_active=True,\n'
        '            )\n'
        '            .first()\n'
        '        )\n'
        '\n'
        '        if not config:\n'
        '            return None\n'
        '\n'
        '        return config\n'
        '\n'
        '    def get(self, request, role_key):\n'
        '        config = self.get_object(role_key)\n'
        '\n'
        '        if not config:\n'
        '            return Response(\n'
        '                {\n'
        '                    "detail": "Role not found."\n'
        '                },\n'
        '                status=status.HTTP_404_NOT_FOUND,\n'
        '            )\n'
        '\n'
        '        return Response(\n'
        '            {\n'
        '                "key": config.role_key,\n'
        '                "name": config.name,\n'
        '                "description": config.description,\n'
        '                "permissions": list(\n'
        '                    config.permissions or []\n'
        '                ),\n'
        '                "editable": True,\n'
        '            }\n'
        '        )\n'
        '\n'
        '    def patch(self, request, role_key):\n'
        '        if role_key == "admin":\n'
        '            return Response(\n'
        '                {\n'
        '                    "detail": (\n'
        '                        "Admin permissions cannot be "\n'
        '                        "modified through this endpoint."\n'
        '                    )\n'
        '                },\n'
        '                status=status.HTTP_400_BAD_REQUEST,\n'
        '            )\n'
        '\n'
        '        config = self.get_object(role_key)\n'
        '\n'
        '        if not config:\n'
        '            return Response(\n'
        '                {\n'
        '                    "detail": "Role not found."\n'
        '                },\n'
        '                status=status.HTTP_404_NOT_FOUND,\n'
        '            )\n'
        '\n'
        '        permissions = request.data.get(\n'
        '            "permissions"\n'
        '        )\n'
        '\n'
        '        if not isinstance(permissions, list):\n'
        '            return Response(\n'
        '                {\n'
        '                    "permissions": [\n'
        '                        "Permissions must be a list."\n'
        '                    ]\n'
        '                },\n'
        '                status=status.HTTP_400_BAD_REQUEST,\n'
        '            )\n'
        '\n'
        '        invalid = [\n'
        '            permission\n'
        '            for permission in permissions\n'
        '            if permission not in VALID_PERMISSION_KEYS\n'
        '        ]\n'
        '\n'
        '        if invalid:\n'
        '            return Response(\n'
        '                {\n'
        '                    "invalid_permissions": invalid\n'
        '                },\n'
        '                status=status.HTTP_400_BAD_REQUEST,\n'
        '            )\n'
        '\n'
        '        config.permissions = list(\n'
        '            dict.fromkeys(permissions)\n'
        '        )\n'
        '        config.save()\n'
        '\n'
        '        return Response(\n'
        '            {\n'
        '                "key": config.role_key,\n'
        '                "name": config.name,\n'
        '                "description": config.description,\n'
        '                "permissions": list(\n'
        '                    config.permissions or []\n'
        '                ),\n'
        '                "editable": True,\n'
        '            }\n'
        '        )\n'
        '\n'
        '\n'
        'class RolePermissionsAPIView(APIView):\n'
        '    """\n'
        '    Returns the editable role permission matrix.\n'
        '\n'
        '    Admin is NOT included as an editable role.\n'
        '    Admin always has full access.\n'
        '    """\n'
        '\n'
        '    permission_classes = [\n'
        '        IsAdminUserRole\n'
        '    ]\n'
        '\n'
        '    def get(self, request):\n'
        '        configs = (\n'
        '            RolePermissionConfig.objects\n'
        '            .filter(is_active=True)\n'
        '            .order_by("role_key")\n'
        '        )\n'
        '\n'
        '        roles = []\n'
        '        for config in configs:\n'
        '            roles.append(\n'
        '                {\n'
        '                    "key": config.role_key,\n'
        '                    "name": config.name,\n'
        '                    "description": config.description,\n'
        '                    "permissions": list(\n'
        '                        config.permissions or []\n'
        '                    ),\n'
        '                    "editable": True,\n'
        '                }\n'
        '            )\n'
        '\n'
        '        custom_roles_qs = (\n'
        '            CustomRole.objects\n'
        '            .prefetch_related("users")\n'
        '        )\n'
        '\n'
        '        custom_roles = []\n'
        '        for role in custom_roles_qs:\n'
        '            custom_roles.append(\n'
        '                {\n'
        '                    "id": role.id,\n'
        '                    "key": f"custom:{role.id}",\n'
        '                    "name": role.name,\n'
        '                    "description": role.description,\n'
        '                    "permissions": list(\n'
        '                        role.permissions or []\n'
        '                    ),\n'
        '                    "editable": True,\n'
        '                    "is_active": role.is_active,\n'
        '                    "user_count": role.users.count(),\n'
        '                }\n'
        '            )\n'
        '\n'
        '        return Response(\n'
        '            {\n'
        '                "roles": roles,\n'
        '                "custom_roles": custom_roles,\n'
        '            }\n'
        '        )\n'
        '\n'
        '\n'
        '# ======================================================\n'
    )

    content = content[:start_idx] + new_block + content[end_idx:]

    with open(path, 'w') as f:
        f.write(content)

    print('OK: replaced RolePermissionsAPIView and added RolePermissionDetailAPIView')