import os, shutil

tmp_dir = 'C:/Users/kripa/AppData/Local/Temp/kilo'
os.makedirs(tmp_dir, exist_ok=True)
tmp_file = os.path.join(tmp_dir, 'categorize_news.py')
path = 'Backend/apps/news/management/commands/categorize_news.py'

content = (
    '"""\n'
    'Management command to categorize existing news articles.\n'
    'Usage:\n'
    '    python manage.py categorize_news\n'
    '    python manage.py categorize_news --all\n'
    '    python manage.py categorize_news --article-id 1\n'
    '    python manage.py categorize_news --force\n'
    '"""\n'
    '\n'
    'from django.core.management.base import BaseCommand\n'
    'from django.conf import settings\n'
    'from apps.news.models import NewsArticle\n'
    'from apps.news.services.categorization import (\n'
    '    categorize_article,\n'
    '    invalidate_company_cache,\n'
    ')\n'
    '\n'
    '\n'
    'class Command(BaseCommand):\n'
    '    help = "Categorize existing news articles using embedding similarity"\n'
    '\n'
    '    def add_arguments(self, parser):\n'
    '        parser.add_argument(\n'
    '            "--all",\n'
    '            action="store_true",\n'
    '            dest="all",\n'
    '            default=False,\n'
    '            help="Categorize all articles",\n'
    '        )\n'
    '        parser.add_argument(\n'
    '            "--article-id",\n'
    '            type=int,\n'
    '            default=None,\n'
    '            help="Categorize a specific article by ID",\n'
    '        )\n'
    '        parser.add_argument(\n'
    '            "--force",\n'
    '            action="store_true",\n'
    '            default=False,\n'
    '            help="Force re-categorization of already processed articles",\n'
    '        )\n'
    '\n'
    '    def handle(self, *args, **options):\n'
    '        invalidate_company_cache()\n'
    '\n'
    '        if options["article_id"]:\n'
    '            try:\n'
    '                article = NewsArticle.objects.get(pk=options["article_id"])\n'
    '            except NewsArticle.DoesNotExist:\n'
    '                self.stderr.write(\n'
    '                    "Article with id={} not found.".format(options["article_id"])\n'
    '                )\n'
    '                return\n'
    '            self._categorize_one(article, force=True)\n'
    '            return\n'
    '\n'
    '        threshold = getattr(\n'
    '            settings, "COMPANY_TAG_SIMILARITY_THRESHOLD", 0.75\n'
    '        )\n'
    '        self.stdout.write("Using similarity threshold: {}".format(threshold))\n'
    '\n'
    '        qs = NewsArticle.objects.all().order_by("-id")\n'
    '        if not options["all"] and not options["force"]:\n'
    '            qs = qs.filter(is_processed=False)\n'
    '\n'
    '        total = qs.count()\n'
    '        self.stdout.write("Found {} articles to process.".format(total))\n'
    '\n'
    '        success = 0\n'
    '        failed = 0\n'
    '        for article in qs.iterator(chunk_size=100):\n'
    '            try:\n'
    '                tags = categorize_article(\n'
    '                    article, force_recompute=options["force"]\n'
    '                )\n'
    '                success += 1\n'
    '                if tags:\n'
    '                    tag_str = ", ".join(\n'
    '                        "{}({:.2f})".format(t.company.symbol, t.confidence)\n'
    '                        for t in tags\n'
    '                    )\n'
    '                    self.stdout.write(\n'
    '                        self.style.SUCCESS(\n'
    '                            "  [{}] {}... -> {}".format(\n'
    '                                article.id, article.headline[:60], tag_str\n'
    '                            )\n'
    '                        )\n'
    '                    )\n'
    '                else:\n'
    '                    self.stdout.write(\n'
    '                        self.style.WARNING(\n'
    '                            "  [{}] {}... -> no tags (needs review)".format(\n'
    '                                article.id, article.headline[:60]\n'
    '                            )\n'
    '                        )\n'
    '                    )\n'
    '            except Exception as exc:\n'
    '                failed += 1\n'
    '                self.stderr.write(\n'
    '                    self.style.ERROR("  [{}] failed: {}".format(article.id, exc))\n'
    '                )\n'
    '\n'
    '        self.stdout.write(\n'
    '            self.style.SUCCESS(\n'
    '                "Categorization complete. Success={}, Failed={}".format(\n'
    '                    success, failed\n'
    '                )\n'
    '            )\n'
    '        )\n'
    '\n'
    '    def _categorize_one(self, article, force=False):\n'
    '        try:\n'
    '            tags = categorize_article(article, force_recompute=force)\n'
    '            if tags:\n'
    '                tag_str = ", ".join(\n'
    '                    "{}({:.2f})".format(t.company.symbol, t.confidence)\n'
    '                    for t in tags\n'
    '                )\n'
    '                self.stdout.write(\n'
    '                    self.style.SUCCESS(\n'
    '                        "  [{}] {}... -> {}".format(\n'
    '                            article.id, article.headline[:60], tag_str\n'
    '                        )\n'
    '                    )\n'
    '                )\n'
    '            else:\n'
    '                self.stdout.write(\n'
    '                    self.style.WARNING(\n'
    '                        "  [{}] {}... -> no tags".format(\n'
    '                            article.id, article.headline[:60]\n'
    '                        )\n'
    '                    )\n'
    '                )\n'
    '        except Exception as exc:\n'
    '            self.stderr.write(\n'
    '                self.style.ERROR("  [{}] failed: {}".format(article.id, exc))\n'
    '            )\n'
)

with open(tmp_file, 'w') as f:
    f.write(content)
shutil.copy(tmp_file, path)
print('OK: wrote categorize_news.py')