# Generated by Django 6.0.7 on 2026-08-30 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open', models.DecimalField(decimal_places=2, max_digits=15)),
                ('high', models.DecimalField(decimal_places=2, max_digits=15)),
                ('low', models.DecimalField(decimal_places=2, max_digits=15)),
                ('close', models.DecimalField(decimal_places=2, max_digits=15)),
                ('volume', models.BigIntegerField()),
                ('turnover', models.DecimalField(decimal_places=2, max_digits=18)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['company', 'date'], name='market_data_company_973846_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'date'), name='unique_company_daily_trading_data')],
            },
        ),
        migrations.CreateModel(
            name='FloorsheetTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('buyer_broker', models.CharField(max_length=100)),
                ('seller_broker', models.CharField(max_length=100)),
                ('quantity', models.BigIntegerField()),
                ('rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('amount', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floorsheet_transactions', to='companies.company')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'date'], name='market_data_company_f5ddb7_idx'), models.Index(fields=['buyer_broker'], name='market_data_buyer_b_a51175_idx'), models.Index(fields=['seller_broker'], name='market_data_seller__3e579a_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'date', 'transaction_id'), name='unique_floorsheet_transaction')],
            },
        ),
    ]
