# Generated by Django 5.1.5 on 2026-08-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_alter_dailyprice_id_alter_floorsheettransaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='floorsheettransaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
