# Generated by Django 5.1.5 on 2026-09-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0003_alter_dailyprice_id_alter_floorsheettransaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyprice',
            name='source',
            field=models.CharField(choices=[('crawled', 'Crawled'), ('seeded', 'Seeded'), ('manual', 'Manual'), ('unverified', 'Unverified')], db_index=True, default='unverified', max_length=16),
        ),
    ]
