# Generated by Django 6.0.7 on 2026-10-02 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_company_logo_url'),
        ('market_data', '0008_broker_tms'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='dailyprice',
            name='ltp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='dailyprice',
            name='prev_close',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='dailyprice',
            name='transactions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DividendAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscal_year', models.CharField(help_text='Nepali fiscal year, e.g. 2081/82.', max_length=20)),
                ('bonus_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('cash_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('book_closure_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividend_announcements', to='companies.company')),
            ],
            options={
                'ordering': ['-book_closure_date', 'company__symbol'],
                'constraints': [models.UniqueConstraint(fields=('company', 'fiscal_year'), name='unique_company_dividend_fiscal_year')],
            },
        ),
    ]
