# Generated by Django 5.1.5 on 2026-09-22 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_id_alter_trackedcompany_id'),
        ('users', '0006_seed_role_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompanyAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, help_text='1 = access granted, 0 = access denied')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['company__name'],
                'constraints': [models.UniqueConstraint(fields=('user', 'company'), name='unique_user_company_access')],
            },
        ),
    ]
