# Generated by Django 5.1.5 on 2026-09-23 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_id_alter_trackedcompany_id'),
        ('users', '0008_watchlist_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercompanyaccess',
            options={},
        ),
        migrations.AlterField(
            model_name='usercompanyaccess',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_company_accesses', to='companies.company'),
        ),
        migrations.AlterField(
            model_name='usercompanyaccess',
            name='status',
            field=models.IntegerField(default=0, help_text='1 = active, 0 = inactive'),
        ),
    ]
