# Generated by Django 6.0.5 on 2026-09-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketBreadthSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('market_session_count', models.PositiveIntegerField(default=0)),
                ('advances', models.PositiveIntegerField(default=0)),
                ('declines', models.PositiveIntegerField(default=0)),
                ('unchanged', models.PositiveIntegerField(default=0)),
                ('return_eligible_count', models.PositiveIntegerField(default=0)),
                ('above_50_dma_count', models.PositiveIntegerField(default=0)),
                ('valid_50_dma_count', models.PositiveIntegerField(default=0)),
                ('above_50_dma_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('above_200_dma_count', models.PositiveIntegerField(default=0)),
                ('valid_200_dma_count', models.PositiveIntegerField(default=0)),
                ('above_200_dma_pct', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ProxyIndexSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('level', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('daily_return_pct', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('eligible_company_count', models.PositiveIntegerField(default=0)),
                ('methodology_version', models.CharField(default='turnover-weighted-v1', max_length=32)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
