# Generated by Django 6.0.5 on 2026-09-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketbreadthsnapshot',
            name='corporate_action_excluded_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proxyindexsnapshot',
            name='corporate_action_excluded_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
