# Generated by Django 6.0.5 on 2026-09-30 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_id_alter_trackedcompany_id'),
        ('market_intelligence', '0002_marketbreadthsnapshot_corporate_action_excluded_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorRotationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('return_1w', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('return_1m', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('return_3m', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('rank_1w', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_1m', models.PositiveIntegerField(blank=True, null=True)),
                ('rank_3m', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_rank_1w', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_rank_1m', models.PositiveIntegerField(blank=True, null=True)),
                ('previous_rank_3m', models.PositiveIntegerField(blank=True, null=True)),
                ('turnover', models.DecimalField(decimal_places=4, default=0, max_digits=22)),
                ('company_count', models.PositiveIntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'sector'],
                'indexes': [models.Index(fields=['date', 'rank_1w'], name='market_inte_date_90bc93_idx')],
                'constraints': [models.UniqueConstraint(fields=('sector', 'date'), name='unique_sector_rotation_snapshot')],
            },
        ),
        migrations.CreateModel(
            name='CompanyTechnicalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('support_20', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('resistance_20', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('support_60', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('resistance_60', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('breakout_20_up', models.BooleanField(blank=True, null=True)),
                ('breakout_20_down', models.BooleanField(blank=True, null=True)),
                ('breakout_55_up', models.BooleanField(blank=True, null=True)),
                ('breakout_55_down', models.BooleanField(blank=True, null=True)),
                ('patterns', models.JSONField(blank=True, default=list)),
                ('dma_50', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('dma_200', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('signal', models.CharField(default='insufficient_history', max_length=32)),
                ('signal_score', models.SmallIntegerField(blank=True, null=True)),
                ('history_sessions', models.PositiveIntegerField(default=0)),
                ('sufficient_history', models.BooleanField(default=False)),
                ('possible_corporate_action', models.BooleanField(default=False)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technical_snapshots', to='companies.company')),
            ],
            options={
                'ordering': ['-date', 'company_id'],
                'indexes': [models.Index(fields=['date', 'signal'], name='market_inte_date_6d60af_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'date'), name='unique_company_technical_snapshot')],
            },
        ),
    ]
