# Generated by Django 6.0.7 on 2026-10-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_intelligence', '0003_sectorrotationsnapshot_companytechnicalsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyindexsnapshot',
            name='equal_weight_level',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='proxyindexsnapshot',
            name='equal_weight_return_pct',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
