# Generated by Django 6.0.7 on 2026-08-30 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('headline', models.TextField()),
                ('body', models.TextField()),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('language', models.CharField(default='unknown', max_length=20)),
                ('sentiment', models.FloatField(blank=True, null=True)),
                ('sentiment_label', models.CharField(blank=True, max_length=20)),
                ('is_processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=1000)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_html', models.TextField(blank=True)),
                ('extraction_error', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleCompanyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('method', models.CharField(max_length=50)),
                ('evidence', models.JSONField(default=dict)),
                ('is_manual', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_tags', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='CategorizationCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_confidence', models.FloatField(blank=True, null=True)),
                ('previous_method', models.CharField(blank=True, max_length=50)),
                ('action', models.CharField(choices=[('add', 'Add'), ('remove', 'Remove'), ('update', 'Update')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorization_corrections', to='companies.company')),
            ],
        ),
    ]
