# Generated by Django 6.0.7 on 2026-08-30 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawler_runs', '0002_rename_prices_created_crawlrun_articles_updated_and_more'),
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categorizationcorrection',
            name='corrected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categorizationcorrection',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='news.newsarticle'),
        ),
        migrations.AddField(
            model_name='articlecompanytag',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_tags', to='news.newsarticle'),
        ),
        migrations.AddField(
            model_name='rawarticle',
            name='crawl_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_articles', to='crawler_runs.crawlrun'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='raw_article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='news.rawarticle'),
        ),
        migrations.AddConstraint(
            model_name='articlecompanytag',
            constraint=models.UniqueConstraint(fields=('article', 'company'), name='unique_article_company_tag'),
        ),
        migrations.AddConstraint(
            model_name='rawarticle',
            constraint=models.UniqueConstraint(fields=('source', 'url'), name='unique_raw_source_url'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['source', 'published_at'], name='news_newsar_source_f6ea0b_idx'),
        ),
        migrations.AddIndex(
            model_name='newsarticle',
            index=models.Index(fields=['content_hash'], name='news_newsar_content_e2a094_idx'),
        ),
    ]
