# Generated by Django 5.1.5 on 2026-09-19 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_articlecompanytag_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='sentiment_error',
            field=models.TextField(blank=True, help_text="Populated only when sentiment_status is 'error'."),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='sentiment_language',
            field=models.CharField(blank=True, help_text='Language detected at scoring time.', max_length=20),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='sentiment_method',
            field=models.CharField(blank=True, help_text='Analyser identifier, so a later model swap is auditable.', max_length=40),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='sentiment_processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='sentiment_status',
            field=models.CharField(choices=[('pending', 'Not yet processed'), ('ok', 'Scored'), ('no_lexicon_match', 'Scored, no tone-bearing vocabulary'), ('insufficient_content', 'Article too short to score'), ('unsupported_language', 'No lexicon for detected language'), ('error', 'Analyser failed')], db_index=True, default='pending', help_text="Lets the frontend distinguish 'sentiment unavailable' from 'sentiment successfully calculated'. A NULL score alone cannot.", max_length=32),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='sentiment',
            field=models.FloatField(blank=True, help_text='Tone score in [-1.0, +1.0]. NULL when unavailable.', null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='sentiment_label',
            field=models.CharField(blank=True, help_text='positive (>= +0.05) / negative (<= -0.05) / neutral.', max_length=20),
        ),
    ]
