# Generated by Django 5.1.5 on 2026-09-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsarticle_sentiment_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='data_provenance',
            field=models.CharField(choices=[('crawled', 'Crawled'), ('seeded', 'Seeded'), ('manual', 'Manual'), ('unverified', 'Unverified')], db_index=True, default='unverified', max_length=16),
        ),
    ]
