# Generated by Django 6.0.7 on 2026-10-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newsarticle_data_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image_url',
            field=models.URLField(blank=True, default='', max_length=1000),
        ),
    ]
