# Generated by Django 6.0.7 on 2026-08-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('vwap', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField()),
                ('volume_average', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('volume_anomaly', models.BooleanField(default=False)),
                ('pressure', models.CharField(choices=[('buying', 'Buying'), ('selling', 'Selling'), ('neutral', 'Neutral')], default='neutral', max_length=20)),
                ('news_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
