# Generated by Django 6.0.7 on 2026-08-30 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyanalysis',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_analysis', to='companies.company'),
        ),
        migrations.AddConstraint(
            model_name='dailyanalysis',
            constraint=models.UniqueConstraint(fields=('company', 'date'), name='unique_daily_analysis'),
        ),
    ]
