# Generated by Django 5.1.5 on 2026-09-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_dailyanalysis_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyanalysis',
            name='pressure_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='dailyanalysis',
            name='volume_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
