# Generated by Django 5.1.5 on 2026-09-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_dailyanalysis_pressure_score_and_more'),
        ('companies', '0005_alter_company_id_alter_trackedcompany_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyanalysis',
            options={'ordering': ['-date'], 'verbose_name_plural': 'Daily analyses'},
        ),
        migrations.AddField(
            model_name='dailyanalysis',
            name='daily_return_pct',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='(close - previous_close) / previous_close * 100.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailyanalysis',
            name='has_sufficient_history',
            field=models.BooleanField(default=False, help_text='True once 20 previous trading sessions are available.'),
        ),
        migrations.AddField(
            model_name='dailyanalysis',
            name='pressure_method',
            field=models.CharField(default='OHLCV_PRICE_VOLUME', help_text='Methodology identifier. OHLCV_PRICE_VOLUME is a published-data proxy and is not evidence of order-book buying or selling.', max_length=40),
        ),
        migrations.AddField(
            model_name='dailyanalysis',
            name='previous_close',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Close of the previous TRADING SESSION. Independent of VWAP.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='dailyanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyanalysis',
            name='volume_baseline_sessions',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many previous sessions the baseline was actually built from.'),
        ),
        migrations.AddField(
            model_name='dailyanalysis',
            name='vwap_30d',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Separate 30-day aggregate summary metric = SUM(turnover) / SUM(volume) across the rolling window. Not the daily VWAP.', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='dailyanalysis',
            name='pressure_score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Deterministic OHLCV score in the range -100 .. +100.', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='dailyanalysis',
            name='volume_anomaly',
            field=models.BooleanField(default=False, help_text='True when volume_ratio >= 1.5 on a full 20-session baseline.'),
        ),
        migrations.AlterField(
            model_name='dailyanalysis',
            name='volume_average',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Mean volume of the PREVIOUS 20 TRADING SESSIONS (not calendar days, and never including this day's own volume).", max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='dailyanalysis',
            name='volume_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='volume / volume_average. NULL when no usable baseline.', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='dailyanalysis',
            name='vwap',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='DAILY VWAP for this trading day = daily turnover / daily volume. NULL when volume is zero or turnover is missing.', max_digits=14, null=True),
        ),
        migrations.AddIndex(
            model_name='dailyanalysis',
            index=models.Index(fields=['company', 'date'], name='analysis_da_company_a1e22c_idx'),
        ),
    ]
