# Generated by Django 5.1.5 on 2026-09-26 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_alter_dailyanalysis_options_and_more'),
        ('companies', '0005_alter_company_id_alter_trackedcompany_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPriceCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('results', models.JSONField(default=dict)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='news_price_correlation', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='VolumeAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('volume', models.BigIntegerField()),
                ('rolling_mean', models.FloatField(blank=True, null=True)),
                ('rolling_std', models.FloatField(blank=True, null=True)),
                ('z_score', models.FloatField(blank=True, null=True)),
                ('pct_of_avg', models.FloatField(blank=True, null=True)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('insufficient_data', models.BooleanField(default=False)),
                ('reason', models.CharField(blank=True, max_length=16)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='volume_anomalies', to='companies.company')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['company', 'date', 'is_anomaly'], name='analysis_vo_company_656dd6_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'date'), name='unique_company_volume_anomaly')],
            },
        ),
    ]
